
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tugasmodul8;

/**
 *
 * @author hp
 */
public class Choosingcharacter extends javax.swing.JFrame {

    /**
     * Creates new form Choosingcharacter
     */
    public Choosingcharacter() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        buttonkazu = new javax.swing.JButton();
        buttonrude = new javax.swing.JButton();
        buttonkinji = new javax.swing.JButton();
        buttonback = new javax.swing.JButton();
        buttondisg = new javax.swing.JButton();
        buttonlej = new javax.swing.JButton();
        buttonbatu = new javax.swing.JButton();
        buttonchad = new javax.swing.JButton();
        buttonling = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Swis721 Hv BT", 1, 36)); // NOI18N
        jLabel1.setText("Choose Your");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(295, 25, 257, 44);

        jLabel2.setFont(new java.awt.Font("Stencil Std", 0, 36)); // NOI18N
        jLabel2.setText("Character");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(311, 75, 231, 37);

        buttonkazu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/Tak berjudul156_20220430133624_1.png"))); // NOI18N
        buttonkazu.setText("     KAZUMA");
        buttonkazu.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        buttonkazu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonkazuActionPerformed(evt);
            }
        });
        jPanel1.add(buttonkazu);
        buttonkazu.setBounds(50, 250, 190, 99);

        buttonrude.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/Tak berjudul157_20220430135601.png"))); // NOI18N
        buttonrude.setText("   RUDEUS");
        buttonrude.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        buttonrude.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonrudeActionPerformed(evt);
            }
        });
        jPanel1.add(buttonrude);
        buttonrude.setBounds(250, 250, 190, 99);

        buttonkinji.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/WhatsApp Image 2022-04-30 at 15.12.01.jpeg"))); // NOI18N
        buttonkinji.setText("  KINJI");
        buttonkinji.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        buttonkinji.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonkinjiActionPerformed(evt);
            }
        });
        jPanel1.add(buttonkinji);
        buttonkinji.setBounds(650, 250, 180, 100);

        buttonback.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/Tak berjudul159_20220430145852.png"))); // NOI18N
        buttonback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonbackActionPerformed(evt);
            }
        });
        jPanel1.add(buttonback);
        buttonback.setBounds(30, 30, 90, 70);

        buttondisg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/WhatsApp Image 2022-04-30 at 14.50.19.jpeg"))); // NOI18N
        buttondisg.setText("  DISGUISE");
        buttondisg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttondisgActionPerformed(evt);
            }
        });
        jPanel1.add(buttondisg);
        buttondisg.setBounds(450, 250, 190, 100);

        buttonlej.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/Tak berjudul161_20220430155619.png"))); // NOI18N
        buttonlej.setText("  LEGEND");
        buttonlej.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonlejActionPerformed(evt);
            }
        });
        jPanel1.add(buttonlej);
        buttonlej.setBounds(640, 400, 180, 100);

        buttonbatu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/WhatsApp Image 2022-04-30 at 15.41.35.jpeg"))); // NOI18N
        buttonbatu.setText("  BATU");
        buttonbatu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonbatuActionPerformed(evt);
            }
        });
        jPanel1.add(buttonbatu);
        buttonbatu.setBounds(60, 400, 180, 100);

        buttonchad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/WhatsApp Image 2022-04-30 at 15.36.10.jpeg"))); // NOI18N
        buttonchad.setText("  CHAD");
        buttonchad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonchadActionPerformed(evt);
            }
        });
        jPanel1.add(buttonchad);
        buttonchad.setBounds(260, 400, 180, 100);

        buttonling.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/WhatsApp Image 2022-04-30 at 16.10.52.jpeg"))); // NOI18N
        buttonling.setText(" LING");
        buttonling.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonlingActionPerformed(evt);
            }
        });
        jPanel1.add(buttonling);
        buttonling.setBounds(450, 400, 180, 100);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/Tak berjudul158_20220430140547.png"))); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(4, 4, 860, 770);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 860, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 770, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>                        

    private void buttonrudeActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
        Rudeus rd = new Rudeus();
        rd.setVisible(true);
        rd.pack();
        rd.setLocationRelativeTo(null);
        rd.setDefaultCloseOperation(Choosingcharacter.EXIT_ON_CLOSE);
    }                                          

    private void buttonkazuActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
        Kazuma kz = new Kazuma();
        kz.setVisible(true);
        kz.pack();
        kz.setLocationRelativeTo(null);
        kz.setDefaultCloseOperation(Choosingcharacter.EXIT_ON_CLOSE);
    }                                          

    private void buttonkinjiActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
        KINJI kj = new KINJI();
        kj.setVisible(true);
        kj.pack();
        kj.setLocationRelativeTo(null);
        kj.setDefaultCloseOperation(Choosingcharacter.EXIT_ON_CLOSE);
    }                                           

    private void buttonbackActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
        Mainmenu mn = new Mainmenu();
        mn.setVisible(true);
        mn.pack();
        mn.setLocationRelativeTo(null);
        mn.setDefaultCloseOperation(Choosingcharacter.EXIT_ON_CLOSE);
    }                                          

    private void buttondisgActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
        Disguiseman dg = new Disguiseman();
        dg.setVisible(true);
        dg.pack();
        dg.setLocationRelativeTo(null);
        dg.setDefaultCloseOperation(Choosingcharacter.EXIT_ON_CLOSE);
    }                                          

    private void buttonbatuActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
        ROCK rk = new ROCK();
        rk.setVisible(true);
        rk.pack();
        rk.setLocationRelativeTo(null);
        rk.setDefaultCloseOperation(Choosingcharacter.EXIT_ON_CLOSE);
    }                                          

    private void buttonchadActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
        Gigachad gc = new Gigachad();
        gc.setVisible(true);
        gc.pack();
        gc.setLocationRelativeTo(null);
        gc.setDefaultCloseOperation(Choosingcharacter.EXIT_ON_CLOSE);
    }                                          

    private void buttonlingActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
        LING lg = new LING();
        lg.setVisible(true);
        lg.pack();
        lg.setLocationRelativeTo(null);
        lg.setDefaultCloseOperation(Choosingcharacter.EXIT_ON_CLOSE);
    }                                          

    private void buttonlejActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
        legend lj = new legend();
        lj.setVisible(true);
        lj.pack();
        lj.setLocationRelativeTo(null);
        lj.setDefaultCloseOperation(Choosingcharacter.EXIT_ON_CLOSE);
        
    }                                         

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Choosingcharacter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Choosingcharacter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Choosingcharacter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Choosingcharacter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Choosingcharacter().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton buttonback;
    private javax.swing.JButton buttonbatu;
    private javax.swing.JButton buttonchad;
    private javax.swing.JButton buttondisg;
    private javax.swing.JButton buttonkazu;
    private javax.swing.JButton buttonkinji;
    private javax.swing.JButton buttonlej;
    private javax.swing.JButton buttonling;
    private javax.swing.JButton buttonrude;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration                   
}
